/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Cliente;
import model.bean.Endereco;

/**
 *
 * @author Alexandre
 */
public class ViewEndereco extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewEndereco
     */
    public ViewEndereco() {
        initComponents();
         initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTTable.getModel();
        jTTable.setRowSorter(new TableRowSorter(modelo));
        
         readJTABLE();
    }
    
     public void readJTABLE(){
        DefaultTableModel modelo = (DefaultTableModel) jTTable.getModel();
        modelo.setNumRows(0);
        EnderecoDAO cdao = new EnderecoDAO();
       
        
        for(Endereco c : cdao.read()){
            modelo.addRow(new Object[]{
                c.getIdendereco(),
                c.getLogadouro(),
                c.getNumero(),
                c.getCidade(),
                c.getEstado(),
                c.getIdcliente().getId(),
                c.getId(),
                c.getNome(),
                c.getEmail()
            });  
        } 
    }
    
    public void readJTABLEForDesc(Integer desc){
        DefaultTableModel modelo = (DefaultTableModel) jTTable.getModel();
        modelo.setNumRows(0);
        EnderecoDAO cdao = new EnderecoDAO();
        
        for(Endereco c : cdao.readForDesc(desc)){
            modelo.addRow(new Object[]{
                c.getIdendereco(),
                c.getLogadouro(),
                c.getNumero(),
                c.getCidade(),
                c.getEstado(),
                c.getIdcliente().getId(),
                c.getId(),
                c.getNome(),
                c.getEmail()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        bntSelecionar = new javax.swing.JButton();
        txtLogadouro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTable = new javax.swing.JTable();
        txtEstado = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        bntEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bntExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bntAlterar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BntTruncate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSelecionar = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Endereços");

        jLabel5.setText("IdCliente");

        bntSelecionar.setText("Selecionar");
        bntSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSelecionarActionPerformed(evt);
            }
        });

        jLabel6.setText("Busca por Id do Cliente.");

        jTTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdEndereço", "Logadouro", "Número", "Cidade", "Estado", "IdCliente", "ID", "Nome", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bntEnviar.setText("Inserir");
        bntEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEnviarActionPerformed(evt);
            }
        });

        jLabel1.setText("Logadouro");

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Número");

        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cidade");

        BntTruncate.setText("Excluir Endereços");
        BntTruncate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntTruncateActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado");

        txtSelecionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSelecionarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BntTruncate)
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntSelecionar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLogadouro)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCidade)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(txtIdCliente))
                                .addGap(136, 136, 136)))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogadouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntSelecionar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bntEnviar)
                        .addComponent(bntExcluir)
                        .addComponent(bntAlterar)
                        .addComponent(BntTruncate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSelecionarActionPerformed
        // TODO add your handling code here:
        readJTABLEForDesc(Integer.parseInt(txtSelecionar.getText()));
    }//GEN-LAST:event_bntSelecionarActionPerformed

    private void jTTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTableMouseClicked
        // TODO add your handling code here:
        if(jTTable.getSelectedRow() != - 1){
            txtIdCliente.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 0).toString());
            txtLogadouro.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 1).toString());
            txtNumero.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 2).toString());
            txtCidade.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 3).toString());
            txtEstado.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 4).toString());
            txtIdCliente.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 5).toString());

            // txtID.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 6).toString());
            // txtNome.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 7).toString());
            // txtEmail.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 8).toString());
        }
    }//GEN-LAST:event_jTTableMouseClicked

    private void bntEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEnviarActionPerformed
        // TODO add your handling code here:
        Endereco c = new Endereco();
        EnderecoDAO dao = new EnderecoDAO();
        Cliente cc = new Cliente();

        c.setLogadouro(txtLogadouro.getText());
        c.setNumero(Integer.parseInt(txtNumero.getText()));
        c.setCidade(txtCidade.getText());
        c.setEstado(txtEstado.getText());
        cc.setId(Integer.parseInt(txtIdCliente.getText()));
        c.setIdcliente(cc);

        dao.create(c);

        txtLogadouro.setText("");
        txtNumero.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtIdCliente.setText("");

        readJTABLE();
    }//GEN-LAST:event_bntEnviarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
        if(jTTable.getSelectedRow() != -1){

            Endereco c = new Endereco();
            EnderecoDAO dao = new EnderecoDAO();

            c.setIdendereco((int)jTTable.getValueAt(jTTable.getSelectedRow(), 0));

            dao.delete(c);

            txtLogadouro.setText("");
            txtNumero.setText("");
            txtCidade.setText("");
            txtEstado.setText("");
            txtIdCliente.setText("");

            readJTABLE();

        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Endereço para excluir !");
        }
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        // TODO add your handling code here:
        if(jTTable.getSelectedRow() != - 1){
            Endereco c = new Endereco();
            EnderecoDAO dao = new EnderecoDAO();
            Cliente cc = new Cliente();

            c.setIdendereco((int)jTTable.getValueAt(jTTable.getSelectedRow(), 0));

            c.setLogadouro(txtLogadouro.getText());
            c.setNumero(Integer.parseInt(txtNumero.getText()));
            c.setCidade(txtCidade.getText());
            c.setEstado(txtEstado.getText());

            cc.setId(Integer.parseInt(txtIdCliente.getText()));
            c.setIdcliente(cc);

            dao.update(c);

            txtIdCliente.setText("");
            txtLogadouro.setText("");
            txtNumero.setText("");
            txtCidade.setText("");
            txtEstado.setText("");

            readJTABLE();

        }
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void BntTruncateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntTruncateActionPerformed
        // TODO add your handling code here:
        if(jTTable.getSelectedRow() != -1){

            Endereco c = new Endereco();
            // EnderecoDAOAO dao = new EnderecoDAOAO();
            EnderecoDAO dao = new EnderecoDAO();
            dao.drop(c);

            txtIdCliente.setText("");
            txtLogadouro.setText("");
            txtNumero.setText("");
            txtCidade.setText("");
            txtEstado.setText("");

            readJTABLE();

        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir a tabela!");
        }

    }//GEN-LAST:event_BntTruncateActionPerformed

    private void txtSelecionarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSelecionarKeyReleased
        // TODO add your handling code here:
        if(jTTable.getSelectedRow() != - 1){
            txtIdCliente.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 0).toString());
            txtLogadouro.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 1).toString());
            txtNumero.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 2).toString());
            txtCidade.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 3).toString());
            txtEstado.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 4).toString());
            txtIdCliente.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 5).toString());

            //txtID.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 6).toString());
            //txtNome.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 7).toString());
            //txtEmail.setText(jTTable.getValueAt(jTTable.getSelectedRow(), 8).toString());
        }

    }//GEN-LAST:event_txtSelecionarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntTruncate;
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntEnviar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTTable;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtLogadouro;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSelecionar;
    // End of variables declaration//GEN-END:variables
}
